// gameDatabase.js - Registry of 66 games for KiddyArcade Ultra

export const CATEGORIES = [
  "All",
  "Action & Runner",
  "Racing & Driving",
  "Board & Strategy",
  "Typing & Word",
  "Sports & Arcade"
];

export const gamesList = [
  // Fully Playable Custom Games
  {
    id: "metro-surfer",
    title: "Metro Surfer",
    category: "Action & Runner",
    playable: true,
    type: "custom",
    description: "Hoverboard through neon subway tunnels! Dodge supersonic hover-trains and collect cyber-coins.",
    mechanics: "Endless 3-lane vertical runner with increasing speed, score multipliers, and hover-boards.",
    controls: ["ArrowLeft / A : Move Left", "ArrowRight / D : Move Right", "ArrowUp / W : Jump", "ArrowDown / S : Slide"],
    difficulty: "Medium",
    xpReward: 120,
    coinReward: 40,
    color: "from-pink-500 to-rose-600",
    icon: "Train"
  },
  {
    id: "temple-escape",
    title: "Temple Escape",
    category: "Action & Runner",
    playable: true,
    type: "custom",
    description: "Flee from the giant cosmic monkey through rotating neon ancient temple pathways!",
    mechanics: "Dynamic lane swapping, jump obstacles, slide under energy barriers, and dodge sharp corners.",
    controls: ["ArrowLeft / A : Move Left / Turn Left", "ArrowRight / D : Move Right / Turn Right", "ArrowUp / W : Jump over obstacles", "ArrowDown / S : Slide under arches"],
    difficulty: "Hard",
    xpReward: 150,
    coinReward: 50,
    color: "from-orange-500 to-amber-600",
    icon: "Compass"
  },
  {
    id: "neon-rider",
    title: "Neon Rider",
    category: "Racing & Driving",
    playable: true,
    type: "custom",
    description: "Drive a glowing high-speed sports car on a synthwave highway. Avoid slow drivers and gather turbo canisters!",
    mechanics: "2.5D perspective racer, speed scales with time, dodge traffic, pick up energy fuel.",
    controls: ["ArrowLeft / A : Steer Left", "ArrowRight / D : Steer Right", "ArrowUp / W : Accelerate / Nitro Boost", "ArrowDown / S : Slow down"],
    difficulty: "Medium",
    xpReward: 130,
    coinReward: 45,
    color: "from-cyan-500 to-blue-600",
    icon: "Car"
  },
  {
    id: "turbo-moto",
    title: "Turbo Moto",
    category: "Racing & Driving",
    playable: true,
    type: "custom",
    description: "Speed through grid highways on an electric superbike. Pull wheelies for double score multipliers!",
    mechanics: "Fast-scrolling bike racer, time trials, nitro boosts, and near-miss points bonuses.",
    controls: ["ArrowLeft / A : Move Left", "ArrowRight / D : Move Right", "ArrowUp / W : Wheelie / Speedup", "Space : Brake"],
    difficulty: "Hard",
    xpReward: 160,
    coinReward: 55,
    color: "from-yellow-400 to-orange-500",
    icon: "Bike"
  },
  {
    id: "chess-royale",
    title: "Chess Royale",
    category: "Board & Strategy",
    playable: true,
    type: "custom",
    description: "Command a futuristic holographic chess army. Duel against a smart cyber-bot or a friend in local co-op.",
    mechanics: "Full standard chess rules with moves validation, highlighting legal moves, and checkmate detection.",
    controls: ["Mouse Click : Select & Place Piece"],
    difficulty: "Hard",
    xpReward: 200,
    coinReward: 80,
    color: "from-violet-600 to-purple-800",
    icon: "Crown"
  },
  {
    id: "carrom-clash",
    title: "Carrom Clash",
    category: "Board & Strategy",
    playable: true,
    type: "custom",
    description: "Flick the striker to pocket your carrom men in a neon glass board with perfect vector physics!",
    mechanics: "Striker positioning, angle adjustment, strike power bar, and bouncy cushion elastic physics.",
    controls: ["Mouse Drag : Position Striker", "Mouse Release : Shoot / Hit Striker"],
    difficulty: "Medium",
    xpReward: 140,
    coinReward: 50,
    color: "from-teal-500 to-emerald-600",
    icon: "Target"
  },
  {
    id: "type-storm",
    title: "Type Storm",
    category: "Typing & Word",
    playable: true,
    type: "custom",
    description: "Unleash electrical bolts by typing fast! Destroy falling meteorites before they obliterate your city.",
    mechanics: "Speed typing, word matching, combo meters, special power words, and screen clearance bomb attacks.",
    controls: ["Keyboard Keys : Type visible words", "Enter / Space : Fire laser beam"],
    difficulty: "Medium",
    xpReward: 125,
    coinReward: 40,
    color: "from-purple-500 to-indigo-600",
    icon: "Keyboard"
  },
  {
    id: "word-invaders",
    title: "Word Invaders",
    category: "Typing & Word",
    playable: true,
    type: "custom",
    description: "Invaders from sector 8 are descending. Type their shields away to save the galaxy!",
    mechanics: "Classic arcade invaders layout, target locking, word difficulty increases as invaders reach bottom.",
    controls: ["Keyboard Keys : Type alien labels"],
    difficulty: "Medium",
    xpReward: 130,
    coinReward: 45,
    color: "from-green-500 to-teal-600",
    icon: "Zap"
  },
  {
    id: "road-roller",
    title: "Road Roller Smash",
    category: "Action & Runner",
    playable: true,
    type: "custom",
    description: "Drive a heavy neon steamroller and crush shipping boxes, walls, and obstacles for score multipliers!",
    mechanics: "Top-down smashing physics, continuous fuel tracking, nitro boosts, and heavy-impact destruction.",
    controls: ["ArrowLeft / A : Turn Left", "ArrowRight / D : Turn Right", "ArrowUp / W : Accelerate Roller", "ArrowDown / S : Reverse"],
    difficulty: "Easy",
    xpReward: 100,
    coinReward: 35,
    color: "from-emerald-400 to-green-600",
    icon: "Hammer"
  },
  {
    id: "truck-challenge",
    title: "Truck Simulator",
    category: "Racing & Driving",
    playable: true,
    type: "custom",
    description: "Steer a mega cargo truck through neon turns. Deliver cyber-crates without dropping any!",
    mechanics: "Steering inertia, cargo balance tracking, checkpoint time limits, and tight-corner driving tasks.",
    controls: ["Arrow Keys / WASD : Steer Truck", "Space : Handbrake"],
    difficulty: "Hard",
    xpReward: 180,
    coinReward: 70,
    color: "from-indigo-500 to-purple-600",
    icon: "Truck"
  },
  {
    id: "connect-4",
    title: "Connect 4",
    category: "Board & Strategy",
    playable: true,
    type: "custom",
    description: "Drop neon chips to match 4 in a row. Play against a simulated online opponent with emoji chat!",
    mechanics: "Grid board chip-dropping, gravity mechanics, diagonal/horizontal/vertical line checks.",
    controls: ["Mouse Click / Hover : Drop Chip in Column"],
    difficulty: "Easy",
    xpReward: 110,
    coinReward: 35,
    color: "from-red-500 to-pink-600",
    icon: "Grid"
  },
  {
    id: "tic-tac-toe",
    title: "Tic-Tac-Toe Neon",
    category: "Board & Strategy",
    playable: true,
    type: "custom",
    description: "The classic game reimagined in glowing 8K neon. Try to beat the smart AI or local companion.",
    mechanics: "Standard 3x3 layout, optimal minimax AI mode, score counters, glowing win lines.",
    controls: ["Mouse Click : Place Marker (X / O)"],
    difficulty: "Easy",
    xpReward: 80,
    coinReward: 20,
    color: "from-pink-500 to-purple-600",
    icon: "Smile"
  },
  {
    id: "snake-neon",
    title: "Snake Neon",
    category: "Sports & Arcade",
    playable: true,
    type: "arcade",
    description: "Navigate a glowing snake in a grid, devouring pixel-gems and growing longer with every bite.",
    mechanics: "Grid-based direction vector movement, fruit generation, collision checks (wall/tail), score counts.",
    controls: ["Arrow Keys / WASD : Direct Snake"],
    difficulty: "Easy",
    xpReward: 90,
    coinReward: 30,
    color: "from-lime-400 to-green-600",
    icon: "Activity"
  },
  {
    id: "breakout-glow",
    title: "Breakout Glow",
    category: "Sports & Arcade",
    playable: true,
    type: "arcade",
    description: "Bounce the plasma ball off your laser-paddle and shatter rows of glowing cyber bricks.",
    mechanics: "Paddle steering, ball bounce angles, power-ups (wider paddle, laser beams, triple-ball), brick structures.",
    controls: ["Mouse Move / ArrowKeys : Steer Paddle", "Space : Launch Ball"],
    difficulty: "Medium",
    xpReward: 115,
    coinReward: 40,
    color: "from-blue-500 to-indigo-600",
    icon: "Layers"
  },
  {
    id: "cyber-pong",
    title: "Cyber Pong",
    category: "Sports & Arcade",
    playable: true,
    type: "arcade",
    description: "Futuristic digital table tennis. Challenge the AI paddle in a duel of reflexes.",
    mechanics: "Ball bounce speeds up on strikes, AI paddles track ball, score counts to 5.",
    controls: ["ArrowUp / ArrowDown / Mouse : Slide Paddle"],
    difficulty: "Easy",
    xpReward: 80,
    coinReward: 20,
    color: "from-cyan-400 to-teal-500",
    icon: "Sliders"
  },
  {
    id: "space-defender",
    title: "Space Defender",
    category: "Sports & Arcade",
    playable: true,
    type: "arcade",
    description: "Command a fighter ship in space and blast descending squadrons of alien invaders.",
    mechanics: "Horizontal ship gliding, bullet shooting, alien descent, score levels, energy shields.",
    controls: ["ArrowLeft / ArrowRight : Gliders", "Space : Shoot lasers"],
    difficulty: "Medium",
    xpReward: 130,
    coinReward: 45,
    color: "from-rose-500 to-violet-600",
    icon: "Shield"
  },
  {
    id: "flappy-neon",
    title: "Flappy Neon",
    category: "Sports & Arcade",
    playable: true,
    type: "arcade",
    description: "Flap the wings of your neon cyber-bird through a forest of high-voltage laser gates.",
    mechanics: "Gravity physics simulation, upward velocity pulse, scrolling level gate barriers.",
    controls: ["Space / Mouse Click : Flap Up"],
    difficulty: "Medium",
    xpReward: 100,
    coinReward: 30,
    color: "from-amber-400 to-red-500",
    icon: "Feather"
  },

  // Interactive Simulator & Mission Games (49 Games)
  {
    id: "monster-truck",
    title: "Monster Truck Mayhem",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Launch massive monster trucks over rows of crushed cars and execute flips in mid-air.",
    mechanics: "Truck engine upgrading, suspension adjustments, stunt scoring simulator, coin payout multipliers.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 30,
    color: "from-red-600 to-orange-700",
    icon: "Flame"
  },
  {
    id: "highway-moto",
    title: "Highway Moto Racer",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Weave between massive trucks and sports cars at high speed. Close calls double your earnings.",
    mechanics: "Traffic density levels, engine tuning, reflex score testing dashboard, bike helmet skin editor.",
    difficulty: "Hard",
    xpReward: 85,
    coinReward: 40,
    color: "from-sky-500 to-indigo-600",
    icon: "Zap"
  },
  {
    id: "formula-neon",
    title: "Formula Neon GP",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Strap into a 1000-horsepower neon formula car and conquer high-speed winding circuits.",
    mechanics: "Tire compound selector, aerodynamics slider, lap time optimizer simulator, pitstop tuning.",
    difficulty: "Hard",
    xpReward: 90,
    coinReward: 45,
    color: "from-emerald-500 to-teal-700",
    icon: "Gauge"
  },
  {
    id: "mud-runner",
    title: "Offroad Mud Runner",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Lock differential gears and crawl through dense swamps, rivers, and high mud banks.",
    mechanics: "Wheel torque levels, winch attachments, tire pressure control, vehicle chassis customizer.",
    difficulty: "Hard",
    xpReward: 95,
    coinReward: 50,
    color: "from-yellow-700 to-amber-900",
    icon: "Compass"
  },
  {
    id: "roller-demo",
    title: "Road Roller Demo",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Drive a heavy steamroller to level old warehouses and concrete walls to clear the road.",
    mechanics: "Smash power multiplier upgrades, weight enhancements, fuel consumption efficiency, wrecking score.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-green-600 to-lime-700",
    icon: "Hammer"
  },
  {
    id: "jet-ski",
    title: "Jet Ski Storm",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Race high-powered water scooters across giant waves and perform ocean flips.",
    mechanics: "Hydro-thrust engine tuning, tail drift coefficients, stunt score simulator, body decals customizer.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-blue-400 to-cyan-600",
    icon: "Waves"
  },
  {
    id: "cyber-kart",
    title: "Cyber Kart",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Race compact go-karts around neon malls using bubble weapons and energy traps.",
    mechanics: "Kart acceleration upgrades, bubble shield capacity, defensive mines, driver avatar editor.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 30,
    color: "from-violet-500 to-pink-500",
    icon: "Sparkles"
  },
  {
    id: "drift-king",
    title: "Drift King",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Slide sideways around tight hairpins to rack up drift points in the neon rain.",
    mechanics: "Tire grip slider, rear differential lock tuning, drift angle simulator, bumper & spoiler attachments.",
    difficulty: "Medium",
    xpReward: 80,
    coinReward: 40,
    color: "from-fuchsia-600 to-rose-700",
    icon: "RefreshCw"
  },
  {
    id: "hovercraft",
    title: "Hovercraft Rider",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Command a cargo hovercraft that floats above mountains, lava, and water hazards.",
    mechanics: "Thruster calibration, shield powerups, cargo weight balance controls, altitude booster simulator.",
    difficulty: "Hard",
    xpReward: 85,
    coinReward: 40,
    color: "from-cyan-600 to-indigo-700",
    icon: "Send"
  },
  {
    id: "cargo-truck",
    title: "Cargo Truck Transporter",
    category: "Racing & Driving",
    playable: false,
    type: "simulator",
    description: "Deliver heavy glowing crystals across narrow mountain edges. Don't let the payload slide off!",
    mechanics: "Payload strap tension control, speed governor, trailer length simulator, wheel configurations.",
    difficulty: "Hard",
    xpReward: 100,
    coinReward: 50,
    color: "from-amber-600 to-yellow-800",
    icon: "Truck"
  },
  {
    id: "tomb-runner",
    title: "Tomb Runner",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Swing on vines, slide down zip-lines, and run along crumbling walls to escape ancient ruins.",
    mechanics: "Rope swing length upgrades, boots friction sliders, stamina boost level, coin magnet upgrade.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 30,
    color: "from-yellow-600 to-orange-700",
    icon: "Compass"
  },
  {
    id: "dino-run",
    title: "Dino Run",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Sprint through volcanic ash and dodge falling meteors as a tiny pixel T-Rex.",
    mechanics: "Feathered jump height, running acceleration boost, dino skin selector, egg nesting bonuses.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-stone-500 to-stone-700",
    icon: "Flame"
  },
  {
    id: "gravity-guy",
    title: "Gravity Guy",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Flip gravity instantly to run on walls and ceilings to escape a high-tech security bot.",
    mechanics: "Gravity flip reaction speed tests, jump booster levels, magnetic armor upgrades, shield duration.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-teal-600 to-cyan-700",
    icon: "ChevronsUpDown"
  },
  {
    id: "jetpack-escape",
    title: "Jetpack Escape",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Strap on a steam-powered jetpack and navigate laboratory corridors dodging electric zappers.",
    mechanics: "Jetpack thrust density upgrades, missile warning indicators, gold coin collector rate, hover height.",
    difficulty: "Medium",
    xpReward: 80,
    coinReward: 38,
    color: "from-blue-600 to-indigo-800",
    icon: "Pocket"
  },
  {
    id: "ninja-dash",
    title: "Ninja Dash",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Slice through flying fruits and dodge incoming shurikens while dashing across treetops.",
    mechanics: "Sword blade lengths, dash velocity upgrades, combo multipliers, smoke bomb reload timer.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-red-600 to-neutral-800",
    icon: "Sword"
  },
  {
    id: "cyber-assassin",
    title: "Cyber Assassin",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Infiltrate neon headquarters, leap across ventilation shafts, and deactivate laser alarms.",
    mechanics: "Grappling hook reach, thermal goggles energy, alarm override speeds, katana sharpness tier.",
    difficulty: "Hard",
    xpReward: 90,
    coinReward: 45,
    color: "from-zinc-700 to-purple-950",
    icon: "EyeOff"
  },
  {
    id: "blob-runner",
    title: "Blob Runner",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Roll a jelly blob along obstacle paths, absorbing smaller gel cups to become massive.",
    mechanics: "Jelly viscosity upgrades, giant bounce speed, spike resistance levels, hat customize screen.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-pink-400 to-purple-500",
    icon: "Smile"
  },
  {
    id: "subway-skate",
    title: "Subway Skate",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Grind on rails and perform kickflips over subway tracks in a digital skater park.",
    mechanics: "Skateboard deck grip, grind wheel velocity, flip trick score multiplier, helmet customizer.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 32,
    color: "from-indigo-600 to-rose-600",
    icon: "Activity"
  },
  {
    id: "slime-climb",
    title: "Sticky Slime Climb",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Launch a sticky slime up bouncy pegs to climb an endless tower while avoiding rising lava.",
    mechanics: "Sticky grip duration upgrades, launch tension levels, lava cooling rates, slime face creator.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 30,
    color: "from-green-400 to-emerald-600",
    icon: "ArrowUpCircle"
  },
  {
    id: "balloon-pop",
    title: "Balloon Pop Blitz",
    category: "Action & Runner",
    playable: false,
    type: "simulator",
    description: "Throw throwing stars at rising balloons. Pop target streaks for bonus rounds.",
    mechanics: "Star throw velocity, balloon burst radius, freeze time upgrades, target multiplier levels.",
    difficulty: "Easy",
    xpReward: 55,
    coinReward: 22,
    color: "from-amber-400 to-rose-500",
    icon: "Target"
  },
  {
    id: "checkers-glow",
    title: "Checkers Glow",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Play draft checkers on a glowing cyber grid, crowning kings with double blast-waves.",
    mechanics: "AI opponent difficulty selector, chip color customization, move timer rules.",
    difficulty: "Medium",
    xpReward: 65,
    coinReward: 30,
    color: "from-violet-500 to-fuchsia-600",
    icon: "Grid"
  },
  {
    id: "reversi",
    title: "Reversi Master",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Trap your opponent's discs between yours to flip them in a board battle of dominance.",
    mechanics: "Move optimizer hints, total disk counter trackers, custom token graphics settings.",
    difficulty: "Hard",
    xpReward: 80,
    coinReward: 40,
    color: "from-teal-600 to-cyan-800",
    icon: "RotateCw"
  },
  {
    id: "ludo",
    title: "Ludo Club",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Roll the lucky dice and move tokens across quadrants. Send opponents back to start!",
    mechanics: "Dice rolling simulator, double-roll chance levels, safe zone shield upgrades, token custom skins.",
    difficulty: "Easy",
    xpReward: 70,
    coinReward: 35,
    color: "from-rose-500 to-amber-500",
    icon: "Grid"
  },
  {
    id: "sudoku",
    title: "Sudoku Neon",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Resolve grid layout challenges, placing numbers 1-9 without duplicate columns or squares.",
    mechanics: "Mistake check limits, highlight matching numbers, layout generator difficulty, pencil draft tool.",
    difficulty: "Hard",
    xpReward: 90,
    coinReward: 45,
    color: "from-indigo-600 to-blue-800",
    icon: "Hash"
  },
  {
    id: "block-puzzle",
    title: "Block Puzzle Jam",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Fit geometric neon blocks into a 10x10 board to clear complete grid lines.",
    mechanics: "Block piece rotator energy, grid cleaning explosives, multiplier streaks, background neon skins.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-pink-500 to-violet-600",
    icon: "Box"
  },
  {
    id: "minesweeper",
    title: "Mine Sweeper Neon",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Read number labels to sweep blank grids without detonating hidden cyber-mines.",
    mechanics: "Mine count density sliders, flag placement indicators, undo-step energy meters, shield batteries.",
    difficulty: "Hard",
    xpReward: 85,
    coinReward: 40,
    color: "from-red-600 to-zinc-800",
    icon: "AlertOctagon"
  },
  {
    id: "dots-boxes",
    title: "Dots & Boxes",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Draw lines between nodes. Claim boxes by enclosing them with the fourth side.",
    mechanics: "Grid size settings, AI thinking profiles, box double-score bonuses, border design editor.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-amber-500 to-orange-600",
    icon: "Square"
  },
  {
    id: "hex-puzzle",
    title: "Hex Puzzle Link",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Place hexagonal tiles to match paths. Join paths from left to right.",
    mechanics: "Path rotation simulator, hint tokens level, tile skin layouts, level difficulty scales.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 32,
    color: "from-cyan-500 to-emerald-600",
    icon: "Share2"
  },
  {
    id: "peg-solitaire",
    title: "Peg Solitaire",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Jump pegs over adjacent ones to remove them, aiming to leave only one peg in the center.",
    mechanics: "Solve solvers, hint logs, peg color settings, board layout modifiers.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-emerald-500 to-teal-600",
    icon: "Circle"
  },
  {
    id: "solitaire",
    title: "Solitaire Classic",
    category: "Board & Strategy",
    playable: false,
    type: "simulator",
    description: "Sort card decks by suit in descending alternating colors. Solve the mystery layout.",
    mechanics: "Draw-1/Draw-3 difficulty, solve autocomplete trigger, card back styles, undo point penalties.",
    difficulty: "Medium",
    xpReward: 80,
    coinReward: 40,
    color: "from-blue-600 to-indigo-700",
    icon: "Layers"
  },
  {
    id: "type-rush",
    title: "Type Rush Racer",
    category: "Typing & Word",
    playable: false,
    type: "simulator",
    description: "Type paragraphs correctly to inject nitrous into your racing kart. Finish first to level up!",
    mechanics: "Words Per Minute (WPM) gauge, accuracy error checking, engine nitrous boost scaling, rival profiles.",
    difficulty: "Hard",
    xpReward: 100,
    coinReward: 50,
    color: "from-blue-500 to-purple-600",
    icon: "Keyboard"
  },
  {
    id: "word-search",
    title: "Word Search Neon",
    category: "Typing & Word",
    playable: false,
    type: "simulator",
    description: "Scan character blocks horizontally, vertically, and diagonally to find listed words.",
    mechanics: "Grid size selector, list count levels, dictionary category (Sports, Sci-fi, Animals), highlight color builder.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-orange-400 to-pink-500",
    icon: "Search"
  },
  {
    id: "hangman",
    title: "Hangman Space",
    category: "Typing & Word",
    playable: false,
    type: "simulator",
    description: "Guess letters correctly to repair the astronaut's space suit oxygen pump.",
    mechanics: "Category vocab selection, hint letters capacity, oxygen tank meters, astronaut suit customization.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 28,
    color: "from-cyan-500 to-blue-500",
    icon: "User"
  },
  {
    id: "anagram",
    title: "Anagram Solver",
    category: "Typing & Word",
    playable: false,
    type: "simulator",
    description: "Rearrange scrambled letters to reveal hidden terms before the clock counts down.",
    mechanics: "Letter shuffling solver, word lists, clock extensions timer, combo streak multipliers.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 32,
    color: "from-pink-500 to-rose-500",
    icon: "RefreshCw"
  },
  {
    id: "word-link",
    title: "Word Link",
    category: "Typing & Word",
    playable: false,
    type: "simulator",
    description: "Swipe connections between letters in the frying pan to fill up cross-word grids.",
    mechanics: "Level builder index, cookie coin rewards, extra words collection, wheel spin multipliers.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-violet-500 to-indigo-600",
    icon: "Link"
  },
  {
    id: "dunk-shot",
    title: "Dunk Shot",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Pull back net launchers to shoot basketballs into consecutive hoops. Don't hit the floor!",
    mechanics: "Trajectory line indicator, ball bounce elasticity, consecutive swish multipliers, net styles editor.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-orange-500 to-red-600",
    icon: "Play"
  },
  {
    id: "ping-pong",
    title: "Table Tennis Pro",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Swipe paddle swipes to add spin and smash ping-pong balls past international opponents.",
    mechanics: "Paddle speed friction, ball spin coefficients, tournament country tree, trophy collections.",
    difficulty: "Medium",
    xpReward: 75,
    coinReward: 35,
    color: "from-cyan-500 to-blue-600",
    icon: "Sliders"
  },
  {
    id: "billiards",
    title: "Billiards 8-Ball",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Aim the cue stick, control force, and shoot solid or striped balls into pockets.",
    mechanics: "Cue ball aim helper line, spin placement (English), elastic collision physics, cue stick skins.",
    difficulty: "Hard",
    xpReward: 85,
    coinReward: 40,
    color: "from-indigo-600 to-zinc-900",
    icon: "Target"
  },
  {
    id: "golf",
    title: "Golf Master",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Aim shots across grass, sand bunkers, and water hazards. Sink the ball under par.",
    mechanics: "Wind velocity vector, green slope indicators, club selection wood/iron/putter, ball color skins.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 32,
    color: "from-emerald-500 to-green-700",
    icon: "Compass"
  },
  {
    id: "air-hockey",
    title: "Air Hockey Glow",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Strike the puck across the ice table and smash it into the opponent's neon slot.",
    mechanics: "Striker table boundaries, bouncy slider coefficient, AI speed tiers, neon board layouts.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 30,
    color: "from-red-500 to-blue-500",
    icon: "Activity"
  },
  {
    id: "archery",
    title: "Archery Hero",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Pull back bows, compensate for wind drift, and hit the bullseye at distant targets.",
    mechanics: "Bow tension multiplier, wind arrow direction, breathing zoom stabilization, custom arrow fletching.",
    difficulty: "Hard",
    xpReward: 80,
    coinReward: 38,
    color: "from-amber-500 to-yellow-600",
    icon: "Target"
  },
  {
    id: "soccer",
    title: "Soccer Penalty Shootout",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Swipe to bend ball shots into corners, and dive as goalie to block incoming strikes.",
    mechanics: "Ball curve swipes, goalkeeper speed levels, cup leagues, stadium cheering noise customizer.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 32,
    color: "from-lime-500 to-emerald-600",
    icon: "Award"
  },
  {
    id: "bowling",
    title: "Bowling Alley",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Position bowling balls, add finger roll spin, and blast ten pins into the gutter.",
    mechanics: "Ball weight levels, lane oil patterns, spin angle adjustments, bowling shoe custom editor.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-purple-600 to-purple-800",
    icon: "Circle"
  },
  {
    id: "fruit-slasher",
    title: "Fruit Slasher",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Slash sweet watermelons, apples, and coconuts in mid-air, avoiding exploding bombs.",
    mechanics: "Slice swipe blade length, bomb trigger filters, combo slice multipliers, background wallpaper shop.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 30,
    color: "from-rose-500 to-red-600",
    icon: "Sword"
  },
  {
    id: "stack-jump",
    title: "Stack Jump",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Jump precisely as stone blocks slide in from sides to build a tall block tower.",
    mechanics: "Slide block speed scaling, perfect alignment score multipliers, character jump skins.",
    difficulty: "Easy",
    xpReward: 60,
    coinReward: 25,
    color: "from-cyan-500 to-teal-500",
    icon: "Layers"
  },
  {
    id: "pacman",
    title: "Pac-Man Neon",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Dash through neon blue corridors, swallowing energy pills and running from colorful ghost bots.",
    mechanics: "Pacman movement speeds, ghost tracking algorithms, power pill duration, fruit bonus levels.",
    difficulty: "Medium",
    xpReward: 80,
    coinReward: 35,
    color: "from-yellow-400 to-blue-600",
    icon: "Ghost"
  },
  {
    id: "bubble-shooter",
    title: "Bubble Shooter",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Aim matching colored bubbles. Match 3 or more bubble connections to make them pop.",
    mechanics: "Bubble trajectory lines, wall bouncing triggers, cluster drops calculations, bubble booster powerups.",
    difficulty: "Easy",
    xpReward: 65,
    coinReward: 28,
    color: "from-pink-500 to-indigo-500",
    icon: "Circle"
  },
  {
    id: "tower-builder",
    title: "Tower Builder",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Release swinging crane hooks to stack skyscraper modules directly on top of each other.",
    mechanics: "Crane sway speed levels, stack balance angles, wind resistance speeds, building themes customizer.",
    difficulty: "Medium",
    xpReward: 70,
    coinReward: 30,
    color: "from-teal-500 to-sky-600",
    icon: "Layers"
  },
  {
    id: "tap-hero",
    title: "Tap Hero Clicker",
    category: "Sports & Arcade",
    playable: false,
    type: "simulator",
    description: "Tap as fast as you can to defeat giant pixel trolls, hire mini-heroes, and loot gold.",
    mechanics: "Click damage levels, automated DPS heroes, critical strike chance, artifact booster upgrades.",
    difficulty: "Easy",
    xpReward: 75,
    coinReward: 40,
    color: "from-amber-500 to-yellow-600",
    icon: "Pointer"
  }
];

// Generates simulated leaderboard entries
export function generateLeaderboard(gameId) {
  const names = [
    "PixelNinja", "CyberKid", "NeonSpeedy", "RoboGamer", "GamerCody", 
    "LootMaster", "RetroMax", "ByteZoe", "DinoRunner", "SpaceAce", 
    "TypeQueen", "ChessStar", "StrikerKing", "RollerSmasher", "TurboRex"
  ];
  
  // Deterministic random generator based on gameId character codes
  const seed = gameId.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const random = (s) => {
    const x = Math.sin(s) * 10000;
    return x - Math.floor(x);
  };

  const scores = [];
  for (let i = 0; i < 5; i++) {
    const nameIdx = Math.floor(random(seed + i) * names.length);
    const scoreVal = Math.floor(2000 + random(seed + i + 10) * 8000);
    scores.push({
      rank: i + 1,
      name: names[nameIdx],
      score: scoreVal
    });
  }
  return scores.sort((a, b) => b.score - a.score).map((s, idx) => ({ ...s, rank: idx + 1 }));
}
